import type { CoreResult, Digest, MessageRemediation } from "../foundation/index.js";

export type RouteGraph = "current" | "published";
export type RouteClaim = Readonly<{ graph: RouteGraph; normalizedRoute: string; owner: string; sourceRevisionId: string }>;
export type RouteGraphSnapshot = Readonly<{ contract: "route-graph-snapshot/v1"; normalization: "route-normalization/v1"; graph: RouteGraph; claims: readonly RouteClaim[]; bytes: Uint8Array; digest: Digest }>;
export type CurrentRouteClaimProposal = Readonly<{ contract: "current-route-claim-proposal/v1"; baselineDigests: Readonly<{ current: Digest; published: Digest }>; claim: RouteClaim; resultingDigests: Readonly<{ current: Digest; published: Digest }>; nextCurrentBytes: Uint8Array }>;
export type PublishedRouteClaimProposal = Readonly<{ contract: "published-route-claim-proposal/v1"; baselineDigests: Readonly<{ current: Digest; published: Digest }>; claim: RouteClaim & Readonly<{ graph: "published" }>; resultingDigests: Readonly<{ current: Digest; published: Digest }>; nextPublishedBytes: Uint8Array }>;
export type RouteClaimReplacementInput = Readonly<{ graph: RouteGraph; owner: string; route: string; sourceRevisionId: string }>;
export type RouteClaimImpactChange = "route-move" | "attribution-only" | "retained";
export type RouteClaimImpact = Readonly<{ change: RouteClaimImpactChange; graph: RouteGraph; owner: string; from: string; to: string; resultingSourceRevisionId: string }>;
export type RouteClaimReplacementProposal = Readonly<{ contract: "route-claim-replacement-proposal/v1"; baselineDigests: Readonly<{ current: Digest; published: Digest }>; claim: RouteClaim; impact: readonly RouteClaimImpact[]; resultingDigests: Readonly<{ current: Digest; published: Digest }>; nextTargetBytes: Uint8Array }>;
export type RouteClaimReplacementResult = Readonly<{ claim: RouteClaim; impact: readonly RouteClaimImpact[]; baselineDigests: Readonly<{ current: Digest; published: Digest }>; resultingDigests: Readonly<{ current: Digest; published: Digest }> }>;
export type SiteDefinitionFailureCode = "INVALID_SITE_DEFINITION_INPUT" | "INVALID_ROUTE" | "ROUTE_CONFLICT" | "ROUTE_CHANGE_REQUIRED" | "ROUTE_CLAIM_NOT_FOUND" | "ROUTE_REPLACEMENT_REQUIRED" | "STALE_ROUTE_PROPOSAL" | "SITE_DEFINITION_STORAGE_FAILURE";
export type SiteDefinitionFailure = Readonly<{ code: SiteDefinitionFailureCode; owner: "SiteDefinition"; subjectIds: readonly string[]; remediation: MessageRemediation }>;
export type SiteDefinitionResult<T> = CoreResult<T> | Readonly<{ ok: false; error: SiteDefinitionFailure }>;
export type SiteDefinitionPortResult<T> = Readonly<{ ok: true; value: T }> | Readonly<{ ok: false; error: unknown }>;
export interface SiteDefinitionTransaction { listRouteClaims(graph: RouteGraph): SiteDefinitionPortResult<readonly RouteClaim[]>; replaceRouteClaim(input: RouteClaim): SiteDefinitionPortResult<RouteClaim>; }
export interface SiteDefinitionPersistence extends SiteDefinitionTransaction { ownsActiveTransaction(transaction: object): boolean; runTransaction<T, E>(operation: (transaction: SiteDefinitionTransaction) => Readonly<{ ok: true; value: T }> | Readonly<{ ok: false; error: E }>): Readonly<{ ok: true; value: T }> | Readonly<{ ok: false; error: E | unknown }>; }
export interface SiteDefinition { snapshot(graph: RouteGraph): SiteDefinitionResult<RouteGraphSnapshot>; prepareCurrentClaim(input: Readonly<{ owner: string; route: string; sourceRevisionId: string }>): SiteDefinitionResult<CurrentRouteClaimProposal>; validateCurrentClaimInTransaction(proposal: CurrentRouteClaimProposal, transaction: SiteDefinitionTransaction): SiteDefinitionResult<ValidatedCurrentRouteClaim>; applyValidatedCurrentClaimInTransaction(token: ValidatedCurrentRouteClaim, transaction: SiteDefinitionTransaction): SiteDefinitionResult<RouteClaim>; createCurrentClaim(input: Readonly<{ owner: string; route: string; sourceRevisionId: string }>): SiteDefinitionResult<RouteClaim>; preparePublishedClaim(input: Readonly<{ owner: string; route: string; sourceRevisionId: string }>): SiteDefinitionResult<PublishedRouteClaimProposal>; validatePublishedClaimInTransaction(proposal: PublishedRouteClaimProposal, transaction: SiteDefinitionTransaction): SiteDefinitionResult<ValidatedPublishedRouteClaim>; applyValidatedPublishedClaimInTransaction(token: ValidatedPublishedRouteClaim, transaction: SiteDefinitionTransaction): SiteDefinitionResult<RouteClaim>; createPublishedClaim(input: Readonly<{ owner: string; route: string; sourceRevisionId: string }>): SiteDefinitionResult<RouteClaim>; prepareRouteClaimReplacement(input: RouteClaimReplacementInput): SiteDefinitionResult<RouteClaimReplacementProposal>; validateRouteClaimReplacementInTransaction(proposal: RouteClaimReplacementProposal, transaction: SiteDefinitionTransaction): SiteDefinitionResult<ValidatedRouteClaimReplacement>; applyValidatedRouteClaimReplacementInTransaction(token: ValidatedRouteClaimReplacement, transaction: SiteDefinitionTransaction): SiteDefinitionResult<RouteClaimReplacementResult>; replaceRouteClaim(input: RouteClaimReplacementInput): SiteDefinitionResult<RouteClaimReplacementResult>; }
export type ValidatedCurrentRouteClaim = Readonly<{ readonly __siteDefinitionToken: unique symbol }>;
export type ValidatedPublishedRouteClaim = Readonly<{ readonly __siteDefinitionPublishedToken: unique symbol }>;
export type ValidatedRouteClaimReplacement = Readonly<{ readonly __siteDefinitionReplacementToken: unique symbol }>;
