export { createTaxonomy } from "./service.js";
export type {
  CreateTaxonomyInput,
  CreateTaxonomyRequest,
  CreateTermCommand,
  DeleteTermCommand,
  MigrateBindingsCommand,
  RenameTermCommand,
  RetireTermCommand,
  RevisionIdentity,
  RevisionTaxonomyBindingUsage,
  RevisionTaxonomyTermBinding,
  Taxonomy,
  TaxonomyBindingMigrationMapping,
  TaxonomyBindingMigrationReplacement,
  TaxonomyCatalog,
  TaxonomyCommand,
  TaxonomyCommandResult,
  TaxonomyFailure,
  TaxonomyFailureCode,
  TaxonomyMigrationResult,
  TaxonomyRecord,
  TaxonomyResult,
  TaxonomySnapshot,
  TaxonomyTermEvidence,
  TaxonomyTermIdentity,
  TaxonomyTermRecord,
  TaxonomyUsageImpact,
} from "./contracts.js";
