import { useEffect, useMemo, useRef, useState } from "react";
import { BrowserRouter, Link, Route, Routes, useNavigate, useParams } from "react-router-dom";

import type { AuthoringSession } from "./authoring-session.js";
import { CmsApiClient, CmsApiError, type ArticleSaveInput } from "./api-client.js";

function slugify(title: string): string { return title.normalize("NFKC").toLowerCase().replace(/[^\p{L}\p{N}]+/gu, "-").replace(/^-+|-+$/gu, ""); }
function message(reason: unknown): string { return reason instanceof CmsApiError ? reason.remediation : "無法完成 CMS request。"; }
function articleContent(value: unknown): Readonly<{ title: string; text: string }> | undefined {
  if (typeof value !== "object" || value === null) return undefined;
  const content = value as Readonly<{ title?: unknown; blocks?: unknown }>;
  const block = Array.isArray(content.blocks) ? content.blocks[0] : undefined;
  return typeof content.title === "string" && typeof block === "object" && block !== null && (block as { kind?: unknown }).kind === "article" && typeof (block as { text?: unknown }).text === "string" ? { title: content.title, text: (block as { text: string }).text } : undefined;
}
function Layout({ children }: Readonly<{ children: React.ReactNode }>): React.JSX.Element { return <><a className="skip" href="#workspace">跳到內容</a><header><p>Browser session 已建立。</p><nav aria-label="CMS 導覽"><Link to="/cms/entries">文章</Link><Link to="/cms/entries/new">新增文章</Link><Link to="/cms/content-types">內容類型</Link></nav></header><main id="workspace">{children}</main></>; }

function ContentTypeList({ api }: Readonly<{ api: CmsApiClient }>): React.JSX.Element {
  const [catalog, setCatalog] = useState<Awaited<ReturnType<CmsApiClient["listContentTypes"]>>>(); const [error, setError] = useState<string>();
  const load = (): void => { setError(undefined); void api.listContentTypes().then(setCatalog).catch((reason: unknown) => setError(message(reason))); };
  useEffect(load, [api]);
  if (catalog === undefined) return <Layout><h1>內容類型</h1>{error === undefined ? <p aria-busy="true">正在載入內容類型。</p> : <><p role="alert">{error}</p><button onClick={load}>重試</button></>}</Layout>;
  return <Layout><h1>內容類型</h1><p aria-live="polite">已載入內容類型。</p>{catalog.items.length === 0 ? <p>尚無內容類型。<Link to="/cms/content-types/new">建立 Article v1</Link></p> : <table><thead><tr><th>識別碼</th><th>版本</th><th>Schema digest</th></tr></thead><tbody>{catalog.items.map((item) => <tr key={`${item.schemaIdentity.schemaId}@${item.schemaIdentity.version}`}><td><Link to={`/cms/content-types/${item.schemaIdentity.schemaId}`}>{item.schemaIdentity.schemaId}</Link></td><td>{item.schemaIdentity.version}</td><td><code>{item.schemaDigest}</code></td></tr>)}</tbody></table>}</Layout>;
}

function CreateArticleType({ api }: Readonly<{ api: CmsApiClient }>): React.JSX.Element {
  const navigate = useNavigate(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const create = async (): Promise<void> => { setBusy(true); setError(undefined); try { await api.createArticleType(); setNotice("已建立 Article v1。"); navigate("/cms/content-types/article", { replace: true }); } catch (reason) { if (reason instanceof CmsApiError && reason.status === 409) { try { await api.getContentType("article"); navigate("/cms/content-types/article", { replace: true }); return; } catch { /* 顯示原始安全錯誤 */ } } setError(message(reason)); } finally { setBusy(false); } };
  return <Layout><h1>建立內容類型</h1><p><strong>schemaId：</strong><output aria-label="鎖定的 schema ID">article</output></p><p>Article v1：非空白標題、單一非空本文 block 與受限 SEO 欄位。</p><p aria-live="polite">{notice}</p>{error !== undefined && <p role="alert">{error}</p>}<button onClick={() => void create()} disabled={busy}>{busy ? "正在建立…" : "建立 Article v1"}</button></Layout>;
}

function ContentTypeDetail({ api }: Readonly<{ api: CmsApiClient }>): React.JSX.Element {
  const { schemaId = "" } = useParams(); const [item, setItem] = useState<Awaited<ReturnType<CmsApiClient["getContentType"]>>>(); const [error, setError] = useState<string>();
  const load = (): void => { setItem(undefined); setError(undefined); void api.getContentType(schemaId).then(setItem).catch((reason: unknown) => setError(message(reason))); };
  useEffect(load, [api, schemaId]);
  return <Layout><h1>內容類型詳細資料</h1>{item === undefined ? error === undefined ? <p aria-busy="true">正在載入內容類型。</p> : <><p role="alert">{error}</p><button onClick={load}>重試</button></> : <><dl><dt>識別碼</dt><dd>{item.schemaIdentity.schemaId}</dd><dt>版本</dt><dd>{item.schemaIdentity.version}</dd><dt>Schema digest</dt><dd><code>{item.schemaDigest}</code></dd></dl><label>唯讀 schema<textarea readOnly aria-label="唯讀 schema" value={JSON.stringify(item.schema, null, 2)} /></label><p aria-live="polite">內容類型已載入。</p></>}</Layout>;
}

function List({ api }: Readonly<{ api: CmsApiClient }>): React.JSX.Element {
  const [catalog, setCatalog] = useState<Awaited<ReturnType<CmsApiClient["getEntries"]>>>(); const [error, setError] = useState<string>(); const [filter, setFilter] = useState<"all" | "draft" | "published">("all");
  const load = (): void => { setError(undefined); void api.getEntries().then(setCatalog).catch((reason: unknown) => setError(message(reason))); };
  useEffect(load, [api]);
  if (catalog === undefined) return <Layout><h1>文章</h1>{error === undefined ? <p aria-busy="true">正在載入文章。</p> : <><p role="alert">{error}</p><button onClick={load}>重試</button></>}</Layout>;
  const items = catalog.items.filter((item) => filter === "all" || filter === "draft" ? filter === "all" || item.status === "draft" : item.status === "published" || item.status === "published-with-draft").sort((left, right) => new Intl.Collator("zh-Hant-TW", { numeric: true, sensitivity: "base" }).compare(left.title, right.title) || left.entryId.localeCompare(right.entryId));
  return <Layout><h1>文章</h1><nav aria-label="文章狀態"><button aria-pressed={filter === "all"} onClick={() => setFilter("all")}>全部</button><button aria-pressed={filter === "draft"} onClick={() => setFilter("draft")}>草稿</button><button aria-pressed={filter === "published"} onClick={() => setFilter("published")}>已發布</button></nav>{items.length === 0 ? <p>尚無文章。<Link to="/cms/entries/new">建立第一篇文章</Link></p> : <table><thead><tr><th>標題</th><th>狀態</th><th>網址</th></tr></thead><tbody>{items.map((item) => <tr key={item.entryId}><td><Link to={`/cms/entries/${item.entryId}`}>{item.title}</Link></td><td>{item.status === "draft" ? "草稿" : item.status === "published" ? "已發布" : "已發布・有未發布變更"}</td><td>{item.current.normalizedRoute}</td></tr>)}</tbody></table>}</Layout>;
}

function Editor({ api, create }: Readonly<{ api: CmsApiClient; create: boolean }>): React.JSX.Element {
  const params = useParams(); const navigate = useNavigate(); const generatedId = useRef(crypto.randomUUID()); const dialog = useRef<HTMLDialogElement>(null); const publishTrigger = useRef<HTMLButtonElement>(null);
  const entryId = params.entryId ?? generatedId.current; const [detail, setDetail] = useState<Awaited<ReturnType<CmsApiClient["getEntry"]>>>(); const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [text, setText] = useState(""); const [saved, setSaved] = useState<Readonly<{ title: string; slug: string; text: string }>>(); const [slugEdited, setSlugEdited] = useState(false); const [loading, setLoading] = useState(true); const [terminal, setTerminal] = useState<string>(); const [error, setError] = useState<string>(); const [notice, setNotice] = useState(""); const [currentPreview, setCurrentPreview] = useState<string>(); const [publishedPreview, setPublishedPreview] = useState<string>();
  const dirty = saved !== undefined && (saved.title !== title || saved.slug !== slug || saved.text !== text); const invalid = { title: title.trim().length === 0, slug: slug.trim().length === 0, text: text.trim().length === 0 };
  const adopt = (next: Awaited<ReturnType<CmsApiClient["getEntry"]>>): void => { const content = articleContent(next.current.revision.content); if (content === undefined) { setTerminal("目前 revision 無法作為 Article 編輯。 "); return; } const fields = { title: content.title, slug: next.current.route.normalizedRoute.slice(1), text: content.text }; setDetail(next); setTitle(fields.title); setSlug(fields.slug); setText(fields.text); setSaved(fields); };
  const preview = async (selection: "current" | "published"): Promise<void> => { try { const document = await api.preview(entryId, selection); if (selection === "current") setCurrentPreview(document.document); else setPublishedPreview(document.document); } catch (reason) { if (selection === "published" && reason instanceof CmsApiError && reason.status === 404) { setPublishedPreview(""); return; } setError(message(reason)); } };
  const load = (): void => { setLoading(true); setTerminal(undefined); setError(undefined); void api.getContentType("article").then(async () => { if (create) { setSaved(undefined); setLoading(false); return; } const next = await api.getEntry(entryId); adopt(next); setLoading(false); await preview("current"); if (next.published !== undefined) await preview("published"); }).catch((reason: unknown) => { if (reason instanceof CmsApiError && reason.status === 404) setTerminal("尚未建立 Article v1，無法儲存文章。"); else setTerminal(message(reason)); setLoading(false); }); };
  useEffect(load, [api, entryId, create]);
  const save = async (): Promise<void> => { if (invalid.title || invalid.slug || invalid.text || terminal !== undefined) { setError("標題、網址代稱與本文皆為必填。"); return; } const input: ArticleSaveInput = { revisionId: crypto.randomUUID(), operationId: crypto.randomUUID(), title, slug, text }; try { await api.save(entryId, input); const refreshed = await api.getEntry(entryId); adopt(refreshed); await preview("current"); setNotice("已儲存，目前預覽已更新。"); setError(undefined); if (create) navigate(`/cms/entries/${entryId}`, { replace: true }); } catch (reason) { setError(reason instanceof CmsApiError && reason.code !== "CMS_RESPONSE_INVALID" ? "已儲存，但重新載入失敗。" : message(reason)); } };
  const publish = async (): Promise<void> => { if (detail === undefined || dirty) return; try { await api.publish(entryId, detail.current.revision.revisionId); const refreshed = await api.getEntry(entryId); adopt(refreshed); await Promise.all([preview("current"), preview("published")]); setNotice("已發布。"); } catch (reason) { setError(message(reason)); } finally { dialog.current?.close(); publishTrigger.current?.focus(); } };
  if (loading) return <Layout><h1>{create ? "新增文章" : "編輯文章"}</h1><p aria-busy="true">正在載入文章。</p></Layout>;
  if (terminal !== undefined) return <Layout><h1>{create ? "新增文章" : "編輯文章"}</h1><p role="alert">{terminal}</p>{terminal.includes("Article v1") ? <Link to="/cms/content-types/new">建立 Article v1</Link> : <button onClick={load}>重試</button>}</Layout>;
  return <Layout><h1>{create ? "新增文章" : "編輯文章"}</h1>{error !== undefined && <p role="alert">{error}</p>}<p aria-live="polite">{notice || (dirty ? "有未儲存的變更；發布已停用。" : "未儲存的變更不會出現在預覽。")}</p><section className="editor"><div><label>標題<input aria-invalid={invalid.title} aria-describedby="title-error" value={title} onChange={(event) => { setTitle(event.target.value); if (!slugEdited) setSlug(slugify(event.target.value)); }} /></label>{invalid.title && <span id="title-error">標題為必填。</span>}<label>網址代稱<input aria-invalid={invalid.slug} aria-describedby="slug-error" value={slug} onChange={(event) => { setSlugEdited(true); setSlug(event.target.value); }} /></label>{invalid.slug && <span id="slug-error">網址代稱為必填。</span>}<label>本文<textarea aria-invalid={invalid.text} aria-describedby="text-error" value={text} onChange={(event) => setText(event.target.value)} /></label>{invalid.text && <span id="text-error">本文為必填。</span>}<button onClick={() => void save()}>儲存草稿</button>{!create && <button ref={publishTrigger} onClick={() => dialog.current?.showModal()} disabled={detail === undefined || dirty}>發布</button>}<dialog ref={dialog} onClose={() => publishTrigger.current?.focus()}><h2>確認發布</h2><p>發布「{saved?.title}」到 /{saved?.slug}（revision {detail?.current.revision.revisionId}）。只移動本機 published pointer，不 build、release 或 deploy。</p><button onClick={() => dialog.current?.close()}>取消</button><button onClick={() => void publish()}>確認發布</button></dialog></div><aside><h2>目前草稿預覽</h2>{currentPreview === undefined ? <p>請先儲存後取得預覽。</p> : <iframe title="目前草稿預覽" sandbox="" referrerPolicy="no-referrer" srcDoc={currentPreview} />}<h2>已發布預覽</h2>{publishedPreview === undefined ? <p>尚未發布</p> : <iframe title="已發布預覽" sandbox="" referrerPolicy="no-referrer" srcDoc={publishedPreview} />}</aside></section></Layout>;
}

export function CmsApp({ session }: Readonly<{ session: AuthoringSession }>): React.JSX.Element { const api = useMemo(() => new CmsApiClient(session), [session]); return <BrowserRouter><Routes><Route path="/cms" element={<List api={api} />} /><Route path="/cms/entries" element={<List api={api} />} /><Route path="/cms/entries/new" element={<Editor api={api} create />} /><Route path="/cms/entries/:entryId" element={<Editor api={api} create={false} />} /><Route path="/cms/content-types" element={<ContentTypeList api={api} />} /><Route path="/cms/content-types/new" element={<CreateArticleType api={api} />} /><Route path="/cms/content-types/:schemaId" element={<ContentTypeDetail api={api} />} /></Routes></BrowserRouter>; }
