import { readFile } from "node:fs/promises";

import { canonicalJsonBytes, copyBytes, isDigest, sha256Digest, type Digest, type JsonValue } from "../foundation/index.js";
import type { ActivePluginSnapshot, CmsEditorBlockResolution, CmsEditorBlockSource, CmsEditorBlockSourceEvidence, CreatePluginHostInput, PluginActivationIdentity, PluginActivationState, PluginDiscoveryReport, PluginHost, PluginHostResult, PluginManifestV1, PreparedSaveRevisionValidators, SaveRevisionContentGuard, SaveRevisionValidatorInput, ValidatedSaveRevisionContent } from "./contracts.js";
import { isCanonicalPluginId, pluginHostError, pluginHostFailure, type PluginHostFailure } from "./failures.js";
import { isExactSemver, readManifest } from "./manifest.js";
import { loadVerifiedPluginModule } from "./module-loader.js";
import { compareCodeUnits } from "./ordering.js";
import { installedPluginDirectories, resolvePluginDirectory, resolvePluginFile, revalidateTrustedRoots, type TrustedRoots, validateTrustedRoots } from "./trusted-root.js";

type Installed = Readonly<{ directory: string; manifest: PluginManifestV1; manifestHash: Digest; entryBytes: Uint8Array }>;
type State = Readonly<{ state: PluginActivationState; digest: Digest }>;
type Prepared = Readonly<{ entryId: string; digest: Digest; callbacks: readonly Readonly<{ identity: PluginActivationIdentity; priority: number; callback: (input: unknown, facade: unknown) => unknown }>[] }>;

function exact(value: unknown, keys: readonly string[]): value is Record<string, unknown> { try { if (value === null || typeof value !== "object" || Array.isArray(value) || Object.getPrototypeOf(value) !== Object.prototype) return false; const descriptors = Object.getOwnPropertyDescriptors(value); return Object.keys(descriptors).length === keys.length && keys.every((key) => key in descriptors && "value" in descriptors[key]!); } catch { return false; } }
function identity(value: unknown): PluginActivationIdentity | null { if (!exact(value, ["id", "version", "hookContract", "manifestHash"]) || !isCanonicalPluginId(value.id) || typeof value.version !== "string" || !isExactSemver(value.version) || value.hookContract !== "plugin-hooks/v1" || typeof value.manifestHash !== "string" || !isDigest(value.manifestHash)) return null; return Object.freeze({ id: value.id, version: value.version, hookContract: value.hookContract, manifestHash: value.manifestHash }); }
function same(left: PluginActivationIdentity, right: PluginActivationIdentity): boolean { return left.id === right.id && left.version === right.version && left.hookContract === right.hookContract && left.manifestHash === right.manifestHash; }
function ordered(values: readonly PluginActivationIdentity[]): readonly PluginActivationIdentity[] { return Object.freeze([...values].map((item) => Object.freeze({ ...item })).sort((a, b) => compareCodeUnits(a.id, b.id))); }
function parseState(value: unknown): PluginActivationState | null { if (!exact(value, ["contract", "active", "reactivationRequired"]) || value.contract !== "plugin-activation-state/v2" || !Array.isArray(value.active) || !Array.isArray(value.reactivationRequired)) return null; const active = value.active.map(identity), reactivationRequired = value.reactivationRequired.map(identity); if (active.some((item) => item === null) || reactivationRequired.some((item) => item === null)) return null; const all = [...active, ...reactivationRequired] as PluginActivationIdentity[]; if (new Set(all.map((item) => item.id)).size !== all.length || ![active, reactivationRequired].every((items) => items.every((item, index) => index === 0 || compareCodeUnits(items[index - 1]!.id, item!.id) < 0))) return null; return Object.freeze({ contract: "plugin-activation-state/v2", active: Object.freeze(active as PluginActivationIdentity[]), reactivationRequired: Object.freeze(reactivationRequired as PluginActivationIdentity[]) }); }
function digest(state: PluginActivationState): Digest | null { const bytes = canonicalJsonBytes(state); return bytes.ok ? sha256Digest(bytes.value) : null; }
function snapshot(state: PluginActivationState, stateDigest: Digest): ActivePluginSnapshot { return Object.freeze({ identities: Object.freeze(state.active.map((item) => Object.freeze({ ...item }))), digest: stateDigest }); }
function evidenceIdentity(item: Installed): PluginActivationIdentity | null { return identity({ id: item.manifest.id, version: item.manifest.version, hookContract: item.manifest.hookContract, manifestHash: item.manifestHash }); }
function json(value: unknown): Readonly<{ value: JsonValue; bytes: Uint8Array; digest: Digest }> | null { const bytes = canonicalJsonBytes(value); if (!bytes.ok) return null; try { return Object.freeze({ value: Object.freeze(JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes.value))) as JsonValue, bytes: copyBytes(bytes.value), digest: sha256Digest(bytes.value) }); } catch { return null; } }

async function installed(roots: TrustedRoots, id: string): Promise<Installed | null> { const directory = await resolvePluginDirectory(roots, id); if (directory === null) return null; const path = await resolvePluginFile(directory, "plugin-manifest.json"); if (path === null) return null; const parsed = await readManifest(path, id); if (!parsed.ok) return null; let entryBytes: Uint8Array | null = null; for (const item of [parsed.value.manifest.entry, ...parsed.value.manifest.resources]) { const file = await resolvePluginFile(directory, item.file); if (file === null) return null; try { const bytes = await readFile(file); if (sha256Digest(bytes) !== item.digest) return null; if (item.file === parsed.value.manifest.entry.file) entryBytes = copyBytes(bytes); } catch { return null; } } return entryBytes === null ? null : Object.freeze({ directory, manifest: parsed.value.manifest, manifestHash: parsed.value.manifestHash, entryBytes }); }

class Host implements PluginHost {
  #queue = Promise.resolve();
  // WeakMap 讓未被 consume 的 snapshot（例如 transaction 在 validator 之前就早退）隨 token 一起回收，不會無限累積。
  #prepared = new WeakMap<PreparedSaveRevisionValidators, Prepared>();
  constructor(private readonly roots: TrustedRoots, private readonly port: CreatePluginHostInput["activationState"]) {}
  async discover(): Promise<PluginHostResult<PluginDiscoveryReport>> { if (!(await revalidateTrustedRoots(this.roots))) return pluginHostError("INVALID_TRUSTED_ROOT"); try { const candidates = []; const rejections: PluginHostFailure[] = []; for (const id of await installedPluginDirectories(this.roots)) { const item = isCanonicalPluginId(id) ? await installed(this.roots, id) : null; if (item === null) { rejections.push(pluginHostFailure("INVALID_PLUGIN_MANIFEST", id)); continue; } candidates.push(Object.freeze({ id: item.manifest.id, version: item.manifest.version, hookContract: item.manifest.hookContract, capabilities: item.manifest.capabilities, manifestHash: item.manifestHash })); } return { ok: true, value: Object.freeze({ candidates: Object.freeze(candidates.sort((a, b) => compareCodeUnits(a.id, b.id))), rejections: Object.freeze(rejections) }) }; } catch { return pluginHostError("PLUGIN_DISCOVERY_FAILED"); } }
  activate(input: Readonly<{ identity: PluginActivationIdentity }>): Promise<PluginHostResult<ActivePluginSnapshot>> { return this.serial(async () => { const wanted = identity(input?.identity); if (wanted === null) return pluginHostError("INVALID_PLUGIN_HOST_INPUT"); const item = await installed(this.roots, wanted.id); if (item === null) return pluginHostError("PLUGIN_EVIDENCE_MISMATCH", wanted.id); const actual = evidenceIdentity(item); if (actual === null) return pluginHostError("PLUGIN_EVIDENCE_MISMATCH", wanted.id); if (!same(wanted, actual)) return pluginHostError("PLUGIN_IDENTITY_CONFLICT", wanted.id); const module = await loadVerifiedPluginModule({ entryBytes: item.entryBytes, manifestHash: item.manifestHash, callbacks: item.manifest.callbacks, pluginId: wanted.id }); if (!module.ok) return module; const current = await this.state(); if (!current.ok) return current; const existing = [...current.value.state.active, ...current.value.state.reactivationRequired].find((entry) => entry.id === wanted.id); if (existing !== undefined && !same(existing, wanted)) return pluginHostError("PLUGIN_IDENTITY_CONFLICT", wanted.id); if (current.value.state.active.some((entry) => same(entry, wanted))) return { ok: true, value: snapshot(current.value.state, current.value.digest) }; const next: PluginActivationState = Object.freeze({ contract: "plugin-activation-state/v2", active: ordered([...current.value.state.active, wanted]), reactivationRequired: ordered(current.value.state.reactivationRequired.filter((entry) => entry.id !== wanted.id)) }); return this.replace(current.value, next); }); }
  deactivate(input: Readonly<{ identity: PluginActivationIdentity }>): Promise<PluginHostResult<ActivePluginSnapshot>> { return this.serial(async () => { const wanted = identity(input?.identity); const current = await this.state(); if (wanted === null) return pluginHostError("INVALID_PLUGIN_HOST_INPUT"); if (!current.ok) return current; if (![...current.value.state.active, ...current.value.state.reactivationRequired].some((entry) => same(entry, wanted))) return pluginHostError("PLUGIN_NOT_ACTIVE", wanted.id); const next: PluginActivationState = Object.freeze({ contract: "plugin-activation-state/v2", active: ordered(current.value.state.active.filter((entry) => entry.id !== wanted.id)), reactivationRequired: ordered(current.value.state.reactivationRequired.filter((entry) => entry.id !== wanted.id)) }); return this.replace(current.value, next); }); }
  getActiveSnapshot(): Promise<PluginHostResult<ActivePluginSnapshot>> { return this.serial(async () => { const current = await this.state(); if (!current.ok) return current; if (current.value.state.reactivationRequired.length > 0) return pluginHostError("ACTIVE_PLUGIN_REACTIVATION_REQUIRED", current.value.state.reactivationRequired[0]!.id); for (const entry of current.value.state.active) { const item = await installed(this.roots, entry.id); if (item === null) return pluginHostError("ACTIVE_PLUGIN_SOURCE_MISSING", entry.id); const actual = evidenceIdentity(item); if (actual === null || !same(entry, actual)) return pluginHostError("ACTIVE_PLUGIN_IDENTITY_MISMATCH", entry.id); } return { ok: true, value: snapshot(current.value.state, current.value.digest) }; }); }
  resolveCmsEditorBlock(input: CmsEditorBlockSource): Promise<PluginHostResult<CmsEditorBlockResolution>> { return this.serial(async () => { if (!exact(input, ["contract", "entryId", "revisionId", "pluginIdentity", "source"]) || input.contract !== "cms-editor-block-source/v1" || typeof input.entryId !== "string" || typeof input.revisionId !== "string") return pluginHostError("INVALID_PLUGIN_HOST_INPUT"); const wanted = identity(input.pluginIdentity), source = json(input.source); if (wanted === null || source === null) return pluginHostError("INVALID_PLUGIN_HOST_INPUT"); const evidence: CmsEditorBlockSourceEvidence = Object.freeze({ ...input, pluginIdentity: wanted, source: source.value, sourceBytes: source.bytes, sourceDigest: source.digest }); const current = await this.state(); if (!current.ok) return current; const item = await installed(this.roots, wanted.id); const actual = item === null ? null : evidenceIdentity(item); const status = item === null ? "missing" : actual === null || !same(wanted, actual) ? "identity-changed" : !current.value.state.active.some((entry) => same(entry, wanted)) ? "inactive" : null; if (status !== null) { const code = status === "missing" ? "PLUGIN_BLOCK_MISSING" : status === "inactive" ? "PLUGIN_BLOCK_INACTIVE" : "PLUGIN_BLOCK_IDENTITY_CHANGED"; return { ok: true, value: Object.freeze({ status, source: evidence, diagnostic: pluginHostFailure(code, wanted.id), activeStateDigest: current.value.digest }) }; } return pluginHostError("PLUGIN_CAPABILITY_DENIED", wanted.id); }); }
  prepareSaveRevisionValidators(input: Readonly<{ entryId: string }>): Promise<PluginHostResult<PreparedSaveRevisionValidators>> { return this.serial(async () => { if (!exact(input, ["entryId"]) || typeof input.entryId !== "string") return pluginHostError("INVALID_PLUGIN_HOST_INPUT"); const current = await this.state(); if (!current.ok) return current; if (current.value.state.reactivationRequired.length > 0) return pluginHostError("ACTIVE_PLUGIN_REACTIVATION_REQUIRED"); const callbacks: Prepared["callbacks"][number][] = []; for (const entry of current.value.state.active) { const item = await installed(this.roots, entry.id); if (item === null) return pluginHostError("ACTIVE_PLUGIN_SOURCE_MISSING", entry.id); const actual = evidenceIdentity(item); if (actual === null || !same(entry, actual)) return pluginHostError("ACTIVE_PLUGIN_IDENTITY_MISMATCH", entry.id); const loaded = await loadVerifiedPluginModule({ entryBytes: item.entryBytes, manifestHash: item.manifestHash, callbacks: item.manifest.callbacks, pluginId: entry.id }); if (!loaded.ok) return loaded; const declaration = item.manifest.callbacks.find((candidate) => candidate.hook === "save-revision/validate"); if (declaration !== undefined) callbacks.push(Object.freeze({ identity: entry, priority: declaration.priority, callback: loaded.value.namespace[declaration.exportName] as (input: unknown, facade: unknown) => unknown })); } callbacks.sort((left, right) => left.priority - right.priority || compareCodeUnits(left.identity.id, right.identity.id)); const token = Object.freeze({ activeStateDigest: current.value.digest, __pluginOperationToken: Symbol("plugin-operation") }) as unknown as PreparedSaveRevisionValidators; this.#prepared.set(token, Object.freeze({ entryId: input.entryId, digest: current.value.digest, callbacks: Object.freeze(callbacks) })); return { ok: true, value: token }; }); }
  runPreparedSaveRevisionValidators(token: PreparedSaveRevisionValidators, input: SaveRevisionValidatorInput, guard: SaveRevisionContentGuard): PluginHostResult<ValidatedSaveRevisionContent> { const prepared = this.#prepared.get(token); if (prepared === undefined || prepared.entryId !== input.entryId) return pluginHostError("INVALID_PLUGIN_OPERATION_SNAPSHOT"); this.#prepared.delete(token); let content = json(input.content); if (content === null) return pluginHostError("PLUGIN_CALLBACK_RESULT_INVALID"); for (const item of prepared.callbacks) { let output: unknown; try { output = item.callback(Object.freeze({ ...input, content: content.value }), Object.freeze({ capability: "save-revision-validator" })); } catch { return pluginHostError("PLUGIN_CALLBACK_FAILED", item.identity.id); } if (output !== null && (typeof output === "object" || typeof output === "function") && typeof (output as { then?: unknown }).then === "function") return pluginHostError("PLUGIN_CALLBACK_RESULT_INVALID", item.identity.id); if (!exact(output, ["contract", "decision"]) && !exact(output, ["contract", "decision", "replacement"])) return pluginHostError("PLUGIN_CALLBACK_RESULT_INVALID", item.identity.id); if (output.contract !== "save-revision-validator-output/v1") return pluginHostError("PLUGIN_CALLBACK_RESULT_INVALID", item.identity.id); if (output.decision === "reject") return pluginHostError("PLUGIN_VALIDATION_REJECTED", item.identity.id); if (output.decision !== "accept" || !exact(output.replacement, ["content"])) return pluginHostError("PLUGIN_CALLBACK_RESULT_INVALID", item.identity.id); content = json(output.replacement.content); if (content === null || !guard({ contentBytes: copyBytes(content.bytes), contentDigest: content.digest }).ok) return pluginHostError("PLUGIN_CALLBACK_RESULT_INVALID", item.identity.id); } return { ok: true, value: Object.freeze({ content: content.value, contentBytes: content.bytes, contentDigest: content.digest, activeStateDigest: prepared.digest }) }; }
  private async state(): Promise<Readonly<{ ok: true; value: State }> | Readonly<{ ok: false; error: PluginHostFailure }>> { try { const state = parseState(await this.port.read()), stateDigest = state === null ? null : digest(state); return state === null || stateDigest === null ? pluginHostError("ACTIVATION_STATE_FAILURE") : { ok: true, value: { state, digest: stateDigest } }; } catch { return pluginHostError("ACTIVATION_STATE_FAILURE"); } }
  private async replace(current: State, next: PluginActivationState): Promise<PluginHostResult<ActivePluginSnapshot>> { try { if (!(await this.port.compareAndReplace({ expectedDigest: current.digest, nextState: next }))) return pluginHostError("ACTIVATION_STATE_CONFLICT"); const nextDigest = digest(next); return nextDigest === null ? pluginHostError("ACTIVATION_STATE_FAILURE") : { ok: true, value: snapshot(next, nextDigest) }; } catch { return pluginHostError("ACTIVATION_STATE_FAILURE"); } }
  private async serial<T>(operation: () => Promise<T>): Promise<T> { const previous = this.#queue; let release: () => void = () => {}; this.#queue = new Promise<void>((resolve) => { release = resolve; }); await previous; try { return await operation(); } finally { release(); } }
}
export async function createPluginHost(input: CreatePluginHostInput): Promise<PluginHostResult<PluginHost>> { if (input === null || typeof input !== "object" || typeof input.activationState?.read !== "function" || typeof input.activationState?.compareAndReplace !== "function") return pluginHostError("INVALID_PLUGIN_HOST_INPUT"); const roots = await validateTrustedRoots(input); return roots === null ? pluginHostError("INVALID_TRUSTED_ROOT") : { ok: true, value: new Host(roots, input.activationState) }; }
