import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import { chromium } from "playwright";

import { createLocalAuthoringClient, createLocalAuthoringCredentialAuthority, startCmsRuntime } from "../../../apps/authoring-api/index.js";
import { runDbMigrate } from "../../../apps/cli/db-migrate.js";
import { runPluginPackage, runThemePackage } from "../../../apps/cli/package.js";
import { canonicalJsonBytes, sha256Digest } from "../../../core/foundation/index.js";
import { migrateDatabase, openPersistence } from "../../../core/persistence/index.js";
import { createTaxonomy } from "../../../core/taxonomy/index.js";
import { runThemeActivate } from "../../../apps/cli/theme-activate.js";

function capture(): Readonly<{ output: string[]; io: Readonly<{ stdout(text: string): void; stderr(text: string): void }> }> {
  const output: string[] = [];
  return { output, io: { stdout: (text) => { output.push(text); }, stderr: (text) => { output.push(text); } } };
}

test("真實 CMS runtime 完成四條 canonical route 的 authenticated browser/a11y journey", async (context) => {
  const root = mkdtempSync(path.join(tmpdir(), "cms-runtime-browser-"));
  context.after(() => { rmSync(root, { recursive: true, force: true }); });
  const repositoryRoot = path.resolve(import.meta.dirname, "../../../");
  const databasePath = path.join(root, "cms.sqlite");
  const mediaRoot = path.join(root, "media");
  const pluginsRoot = path.join(root, "plugins");
  const themesRoot = path.join(root, "themes");
  const credentialRoot = path.join(root, "credential");
  mkdirSync(mediaRoot, { mode: 0o700 });
  mkdirSync(pluginsRoot, { mode: 0o700 });
  mkdirSync(themesRoot, { mode: 0o700 });
  assert.equal(runDbMigrate(["--database", databasePath], capture().io), 0);
  assert.equal(await runPluginPackage(["--id", "seo-basics", "--installed-plugins-root", pluginsRoot], capture().io), 0);
  assert.equal(await runThemePackage(["--id", "study-notes", "--installed-themes-root", themesRoot], capture().io), 0);
  assert.equal(await runThemeActivate(["--database", databasePath, "--installed-themes-root", themesRoot, "--id", "study-notes"], capture().io), 0);
  const credential = createLocalAuthoringCredentialAuthority({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
  assert.equal((await credential.transition("provision")).ok, true);
  const runtime = await startCmsRuntime({ repositoryRoot, databasePath, mediaRoot, installedPluginsRoot: pluginsRoot, installedThemesRoot: themesRoot, cmsAssetsRoot: path.join(repositoryRoot, "dist", "cms"), credential: { homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }, logger: () => undefined });
  assert.equal(runtime.ok, true, runtime.ok ? "" : runtime.error.code);
  if (!runtime.ok) return;
  let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
  try {
    const minted = await createLocalAuthoringClient({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }).mintBrowserTicket();
    assert.equal(minted.ok, true, minted.ok ? "" : minted.error.code);
    if (!minted.ok) return;
    browser = await chromium.launch();
    const context_ = await browser.newContext({ serviceWorkers: "block", acceptDownloads: false, viewport: { width: 1440, height: 900 } });
    const page = await context_.newPage();
    await page.goto(`${runtime.value.origin}/cms#${minted.value.ticket}`, { waitUntil: "networkidle" });
    await page.getByRole("heading", { name: "CMS 文章工作台", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms");
    assert.equal(await page.getByText("Browser session 已建立。", { exact: true }).count(), 1);
    assert.equal(await page.getByRole("main").getAttribute("aria-labelledby"), "page-title");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    await page.getByRole("link", { name: "跳到主標題", exact: true }).focus();
    await page.keyboard.press("Enter");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    await page.getByRole("link", { name: "文章", exact: true }).click();
    await page.getByRole("heading", { name: "文章全覽", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/entries");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    await page.getByRole("link", { name: "建立第一篇文章", exact: true }).click();
    await page.getByRole("heading", { name: "新增文章", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/entries/new");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    await page.getByRole("textbox", { name: "標題", exact: true }).fill("Runtime Article v1");
    await page.getByRole("textbox", { name: "網址代稱", exact: true }).fill("runtime-article");
    await page.getByRole("textbox", { name: "本文", exact: true }).fill("第一版真實 runtime 內容");
    await page.getByRole("button", { name: "儲存", exact: true }).click();
    await page.getByRole("heading", { name: "編輯文章", exact: true }).waitFor();
    await page.waitForFunction(() => /^\/cms\/entries\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u.test(location.pathname));
    assert.match(new URL(page.url()).pathname, /^\/cms\/entries\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u);
    const entryId = new URL(page.url()).pathname.split("/").at(-1) ?? "";
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    const currentFrame = page.getByTitle("目前版本頁面預覽", { exact: true });
    await currentFrame.waitFor();
    assert.equal(await currentFrame.getAttribute("sandbox"), "");
    const currentPreview = currentFrame.contentFrame();
    assert.ok(currentPreview);
    await currentPreview.getByText("Runtime Article v1", { exact: true }).waitFor();
    const currentTab = page.getByRole("tab", { name: "目前版本", exact: true });
    const publishedTab = page.getByRole("tab", { name: "已發布版本", exact: true });
    await currentTab.focus();
    await page.keyboard.press("ArrowRight");
    assert.equal(await publishedTab.getAttribute("aria-selected"), "true");
    await page.keyboard.press("ArrowRight");
    assert.equal(await currentTab.getAttribute("aria-selected"), "true");
    const publish = page.getByRole("button", { name: "發布", exact: true });
    await publish.click();
    const dialog = page.getByRole("dialog", { name: "發布文章", exact: true });
    await dialog.waitFor();
    assert.match(await dialog.textContent() ?? "", /將發布目前 revision：/u);
    const cancel = dialog.getByRole("button", { name: "取消", exact: true });
    const confirm = dialog.getByRole("button", { name: "確認發布", exact: true });
    await confirm.focus();
    await page.keyboard.press("Tab");
    assert.equal(await page.evaluate(() => document.activeElement?.textContent), "取消");
    await cancel.focus();
    await page.keyboard.press("Shift+Tab");
    assert.equal(await page.evaluate(() => document.activeElement?.textContent), "確認發布");
    await page.keyboard.press("Escape");
    await page.waitForFunction(() => !document.querySelector("dialog")?.open);
    assert.equal(await page.evaluate(() => document.activeElement?.textContent), "發布");
    await publishedTab.click();
    await page.getByText("尚未發布", { exact: true }).waitFor();
    await publish.click();
    await confirm.click();
    await page.getByText("已發布。", { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => document.activeElement?.textContent), "已發布。");
    await publishedTab.click();
    const publishedFrame = page.getByTitle("已發布版本頁面預覽", { exact: true });
    await publishedFrame.waitFor();
    assert.equal(await publishedFrame.getAttribute("sandbox"), "");
    const publishedPreview = publishedFrame.contentFrame();
    assert.ok(publishedPreview);
    await publishedPreview.getByText("Runtime Article v1", { exact: true }).waitFor();
    await page.setViewportSize({ width: 375, height: 844 });
    await page.getByRole("textbox", { name: "標題", exact: true }).fill("Runtime Article v2");
    await page.getByRole("button", { name: "儲存", exact: true }).click();
    await page.getByText("已儲存。", { exact: true }).waitFor();
    await page.getByRole("button", { name: "儲存", exact: true }).scrollIntoViewIfNeeded();
    await currentTab.click();
    const refreshedCurrentPreview = page.getByTitle("目前版本頁面預覽", { exact: true }).contentFrame();
    assert.ok(refreshedCurrentPreview);
    await refreshedCurrentPreview.getByText("Runtime Article v2", { exact: true }).waitFor();
    await publishedTab.click();
    const refreshedPublishedPreview = page.getByTitle("已發布版本頁面預覽", { exact: true }).contentFrame();
    assert.ok(refreshedPublishedPreview);
    await refreshedPublishedPreview.getByText("Runtime Article v1", { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.getByRole("link", { name: "文章", exact: true }).click();
    await page.getByText("已發布，有未發布變更", { exact: true }).waitFor();
    const mediaLibrary = page.getByRole("link", { name: "媒體庫", exact: true });
    await mediaLibrary.focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "媒體庫", exact: true }).waitFor();
    await page.getByText("尚無媒體。").waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/media");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    await page.getByRole("link", { name: "匯入第一個媒體檔案", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "匯入媒體", exact: true }).waitFor();
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    await page.getByRole("textbox", { name: "Metadata JSON", exact: true }).fill("{");
    await page.getByRole("button", { name: "匯入媒體", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.locator("#media-asset-id-error").waitFor();
    assert.equal(await page.locator("#media-asset-id").getAttribute("aria-describedby"), "media-asset-id-error");
    assert.equal(await page.locator("#media-version-id").getAttribute("aria-describedby"), "media-version-id-error");
    assert.equal(await page.locator("#media-file").getAttribute("aria-describedby"), "media-file-error");
    assert.equal(await page.locator("#media-metadata").getAttribute("aria-describedby"), "media-metadata-error");
    await page.getByRole("textbox", { name: "Asset ID", exact: true }).fill("runtime-media");
    await page.getByRole("textbox", { name: "Version ID", exact: true }).fill("v1");
    await page.getByLabel("媒體檔案", { exact: true }).setInputFiles({ name: "runtime.txt", mimeType: "text/plain", buffer: Buffer.from("runtime media") });
    await page.getByRole("textbox", { name: "Metadata JSON", exact: true }).fill("{\"mime\":\"text/plain\"}");
    const importStarted = Promise.withResolvers<void>();
    const releaseImport = Promise.withResolvers<void>();
    await page.route("**/v1/media/import", async (route) => {
      if (route.request().method() === "POST") { importStarted.resolve(); await releaseImport.promise; }
      await route.continue();
    });
    await page.getByRole("button", { name: "匯入媒體", exact: true }).focus();
    await page.keyboard.press("Enter");
    await importStarted.promise;
    const importForm = page.getByRole("form", { name: "媒體匯入", exact: true });
    assert.equal(await importForm.getAttribute("aria-busy"), "true");
    const importStatus = importForm.getByRole("status");
    assert.equal(await importStatus.getAttribute("aria-live"), "polite");
    await importStatus.getByText("正在匯入。", { exact: true }).waitFor();
    releaseImport.resolve();
    await page.getByRole("heading", { name: "媒體：runtime-media", exact: true }).waitFor();
    await page.unroute("**/v1/media/import");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const importedStatus = page.getByText("已匯入 version：v1", { exact: true });
    await importedStatus.waitFor();
    assert.equal(await importedStatus.getAttribute("aria-live"), "polite");
    page.once("dialog", (dialog) => dialog.accept());
    await page.getByRole("button", { name: "封存", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.getByText("archived", { exact: true }).waitFor();
    page.once("dialog", (dialog) => dialog.accept());
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
    await page.getByRole("button", { name: "復原", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.getByText("ready", { exact: true }).waitFor();
    const client = createLocalAuthoringClient({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
    const verified = openPersistence({ databasePath });
    assert.equal(verified.ok, true, verified.ok ? "" : verified.error.code);
    if (!verified.ok) return;
    const pointers = verified.value.getEntryPointers(entryId);
    verified.value.close();
    assert.equal(pointers.ok, true, pointers.ok ? "" : pointers.error.code);
    if (!pointers.ok) return;
    const pinned = await client.saveRevision({ entryId, request: { contract: "save-revision-request/v1", revisionId: "runtime-media-published", operationId: "runtime-media-published-save", expectedCurrentRevisionId: pointers.value.currentRevisionId, schemaIdentity: { schemaId: "site-content", version: 1 }, content: { contract: "site-content/v1", title: "Runtime Article v1", blocks: [{ kind: "article", text: "第一版真實 runtime 內容" }], seo: {} }, route: "/runtime-article", assetVersions: [{ assetId: "runtime-media", assetVersionId: "v1" }], taxonomyTerms: [] } });
    assert.equal(pinned.ok, true, pinned.ok ? "" : pinned.error.code);
    if (!pinned.ok) return;
    const pinnedPublished = await client.publishRevision({ entryId, request: { contract: "publish-revision-request/v1", expectedCurrentRevisionId: pinned.value.pointer.currentRevisionId, operationId: "runtime-media-published-publish" } });
    assert.equal(pinnedPublished.ok, true, pinnedPublished.ok ? "" : pinnedPublished.error.code);
    if (!pinnedPublished.ok) return;
    const publishedRevisionId = pinnedPublished.value.publishedPointer.publishedRevisionId;
    assert.equal(publishedRevisionId, pinned.value.pointer.currentRevisionId);
    const pinnedStore = openPersistence({ databasePath });
    assert.equal(pinnedStore.ok, true, pinnedStore.ok ? "" : pinnedStore.error.code);
    if (!pinnedStore.ok) return;
    try {
      assert.deepEqual(pinnedStore.value.getRevisionReferences({ entryId, revisionId: publishedRevisionId }), { ok: true, value: [{ revision: { entryId, revisionId: publishedRevisionId }, assetVersion: { assetId: "runtime-media", assetVersionId: "v1" } }] });
    } finally { pinnedStore.value.close(); }
    const referenced = await client.saveRevision({ entryId, request: { contract: "save-revision-request/v1", revisionId: "runtime-media-reference", operationId: "runtime-media-reference-save", expectedCurrentRevisionId: publishedRevisionId, schemaIdentity: { schemaId: "site-content", version: 1 }, content: { contract: "site-content/v1", title: "Runtime Article v2", blocks: [{ kind: "article", text: "第一版真實 runtime 內容" }], seo: {} }, route: "/runtime-article", assetVersions: [{ assetId: "runtime-media", assetVersionId: "v1" }], taxonomyTerms: [] } });
    assert.equal(referenced.ok, true, referenced.ok ? "" : referenced.error.code);
    if (!referenced.ok) return;
    assert.notEqual(referenced.value.pointer.currentRevisionId, publishedRevisionId);
    assert.equal(referenced.value.pointer.publishedRevisionId, publishedRevisionId);
    await page.getByRole("link", { name: "返回媒體庫", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "媒體庫", exact: true }).waitFor();
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    await page.getByRole("link", { name: "runtime-media", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "媒體：runtime-media", exact: true }).waitFor();
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    await page.getByRole("heading", { name: "替換目前引用", exact: true }).waitFor();
    await page.locator("#media-replacement-file").setInputFiles({ name: "runtime-replacement.txt", mimeType: "text/plain", buffer: Buffer.from("replacement bytes") });
    page.once("dialog", (dialog) => dialog.accept());
    await page.getByRole("button", { name: "建立 replacement version", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.waitForFunction(() => document.querySelectorAll("table tbody tr").length === 2);
    const replacedStore = openPersistence({ databasePath });
    assert.equal(replacedStore.ok, true, replacedStore.ok ? "" : replacedStore.error.code);
    if (!replacedStore.ok) return;
    try {
      const after = replacedStore.value.getEntryPointers(entryId);
      assert.equal(after.ok, true);
      if (!after.ok) return;
      assert.notEqual(after.value.currentRevisionId, referenced.value.pointer.currentRevisionId);
      assert.equal(after.value.publishedRevisionId, publishedRevisionId);
      const currentReferences = replacedStore.value.getRevisionReferences({ entryId, revisionId: after.value.currentRevisionId });
      const publishedReferences = replacedStore.value.getRevisionReferences({ entryId, revisionId: publishedRevisionId });
      assert.equal(currentReferences.ok && publishedReferences.ok, true);
      if (!currentReferences.ok || !publishedReferences.ok) return;
      assert.deepEqual(currentReferences.value.map((item) => item.assetVersion.assetId), ["runtime-media"]);
      assert.notEqual(currentReferences.value[0]?.assetVersion.assetVersionId, "v1");
      assert.deepEqual(publishedReferences.value.map((item) => item.assetVersion), [{ assetId: "runtime-media", assetVersionId: "v1" }]);
    } finally { replacedStore.value.close(); }
    // 封存仍被 published pointer 引用的版本必須被拒絕，且 CMS 要顯示契約要求的完整 published 引用。
    const publishedRow = page.locator("tbody tr").filter({ has: page.locator("td", { hasText: /^v1$/u }) });
    page.once("dialog", (dialog) => dialog.accept());
    await publishedRow.getByRole("button", { name: "封存", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.getByRole("alert").getByText(`仍被已發布內容引用，無法封存此媒體版本。目前引用：${entryId} / ${publishedRevisionId}`, { exact: true }).waitFor();
    await publishedRow.getByText("ready", { exact: true }).waitFor();
    const missingTicket = await client.mintBrowserTicket();
    assert.equal(missingTicket.ok, true, missingTicket.ok ? "" : missingTicket.error.code);
    if (!missingTicket.ok) return;
    const missingPage = await (await browser.newContext({ serviceWorkers: "block", acceptDownloads: false })).newPage();
    await missingPage.goto(`${runtime.value.origin}/cms/media/missing-media#${missingTicket.value.ticket}`, { waitUntil: "networkidle" });
    await missingPage.getByRole("heading", { name: "媒體詳情", exact: true }).waitFor();
    await missingPage.getByText("找不到媒體 asset。", { exact: true }).waitFor();
    await missingPage.waitForFunction(() => document.activeElement?.id === "page-title");
  } finally {
    await browser?.close();
    await runtime.value.close();
  }
});

test("真實 CMS runtime 完成 taxonomy list、create 與 detail browser/a11y journey", async (context) => {
  const root = mkdtempSync(path.join(tmpdir(), "cms-taxonomy-workspace-browser-"));
  context.after(() => { rmSync(root, { recursive: true, force: true }); });
  const repositoryRoot = path.resolve(import.meta.dirname, "../../../");
  const databasePath = path.join(root, "cms.sqlite");
  const mediaRoot = path.join(root, "media");
  const pluginsRoot = path.join(root, "plugins");
  const themesRoot = path.join(root, "themes");
  const credentialRoot = path.join(root, "credential");
  mkdirSync(mediaRoot, { mode: 0o700 });
  mkdirSync(pluginsRoot, { mode: 0o700 });
  mkdirSync(themesRoot, { mode: 0o700 });
  assert.equal(runDbMigrate(["--database", databasePath], capture().io), 0);
  assert.equal(await runThemePackage(["--id", "study-notes", "--installed-themes-root", themesRoot], capture().io), 0);
  assert.equal(await runThemeActivate(["--database", databasePath, "--installed-themes-root", themesRoot, "--id", "study-notes"], capture().io), 0);
  const credential = createLocalAuthoringCredentialAuthority({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
  assert.equal((await credential.transition("provision")).ok, true);
  const runtime = await startCmsRuntime({ repositoryRoot, databasePath, mediaRoot, installedPluginsRoot: pluginsRoot, installedThemesRoot: themesRoot, cmsAssetsRoot: path.join(repositoryRoot, "dist", "cms"), credential: { homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }, logger: () => undefined });
  assert.equal(runtime.ok, true, runtime.ok ? "" : runtime.error.code);
  if (!runtime.ok) return;
  let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
  try {
    const client = createLocalAuthoringClient({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
    const minted = await client.mintBrowserTicket();
    assert.equal(minted.ok, true, minted.ok ? "" : minted.error.code);
    if (!minted.ok) return;
    browser = await chromium.launch();
    const page = await (await browser.newContext({ serviceWorkers: "block", acceptDownloads: false, viewport: { width: 1440, height: 900 } })).newPage();
    const taxonomiesPath = `${runtime.value.origin}/v1/taxonomies`;
    let releaseCatalog: (() => void) | undefined;
    const catalogHeld = new Promise<void>((resolve) => { releaseCatalog = resolve; });
    await page.route(taxonomiesPath, async (route) => {
      if (route.request().method() === "GET") await catalogHeld;
      await route.continue();
    });
    await page.goto(`${runtime.value.origin}/cms#${minted.value.ticket}`, { waitUntil: "domcontentloaded" });
    await page.getByRole("heading", { name: "CMS 文章工作台", exact: true }).waitFor();
    const skip = page.getByRole("link", { name: "跳到主標題", exact: true });
    await skip.focus();
    assert.equal(await skip.evaluate((element) => document.activeElement === element), true);
    assert.equal(await skip.evaluate((element) => getComputedStyle(element).outlineStyle), "solid");
    await page.keyboard.press("Enter");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const taxonomies = page.getByRole("link", { name: "分類", exact: true });
    await taxonomies.focus();
    assert.equal(await taxonomies.evaluate((element) => document.activeElement === element), true);
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "分類全覽", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/taxonomies");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const loading = page.locator('p[role="status"][aria-busy="true"]');
    await loading.waitFor();
    assert.equal(await loading.textContent(), "正在載入分類。");
    releaseCatalog?.();
    await page.getByText("尚無分類。", { exact: false }).waitFor();
    await page.unroute(taxonomiesPath);
    const createFirst = page.getByRole("link", { name: "建立第一個分類", exact: true });
    await createFirst.focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "建立分類", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/taxonomies/new");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const taxonomyId = page.getByRole("textbox", { name: "Taxonomy ID", exact: true });
    const taxonomyLabel = page.getByRole("textbox", { name: "分類名稱", exact: true });
    const submit = page.getByRole("button", { name: "建立分類", exact: true });
    await taxonomyId.fill("topics/invalid");
    await taxonomyLabel.fill("主題");
    await submit.focus();
    await page.keyboard.press("Enter");
    await page.locator("#taxonomy-id-error").waitFor();
    assert.equal(await taxonomyId.getAttribute("aria-invalid"), "true");
    assert.equal(await taxonomyId.getAttribute("aria-describedby"), "taxonomy-id-error");
    assert.equal(await page.locator("#taxonomy-id-error").getAttribute("role"), "alert");
    await taxonomyId.fill("topics");
    let releaseCreate: (() => void) | undefined;
    const createHeld = new Promise<void>((resolve) => { releaseCreate = resolve; });
    await page.route(taxonomiesPath, async (route) => {
      if (route.request().method() === "POST") await createHeld;
      await route.continue();
    });
    await submit.focus();
    await page.keyboard.press("Enter");
    const creating = page.locator('p[role="status"]').filter({ hasText: "正在建立分類。" });
    await creating.waitFor();
    assert.equal(await page.getByRole("form", { name: "分類定義", exact: true }).getAttribute("aria-busy"), "true");
    releaseCreate?.();
    await page.getByRole("heading", { name: "分類：主題", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/taxonomies/topics");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const created = page.locator('p[role="status"]').filter({ hasText: "已建立分類。" });
    await created.waitFor();
    assert.equal(await created.getAttribute("aria-live"), "polite");
    await page.getByText("Taxonomy ID", { exact: true }).waitFor();
    await page.getByText("topics", { exact: true }).waitFor();
    await page.getByRole("heading", { name: "Terms", exact: true }).waitFor();
    await page.getByText("尚無 term。", { exact: true }).waitFor();
    await page.unroute(taxonomiesPath);
    await taxonomies.focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "分類全覽", exact: true }).waitFor();
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const create = page.getByRole("link", { name: "建立分類", exact: true });
    await create.focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "建立分類", exact: true }).waitFor();
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    await taxonomyId.fill("topics");
    await taxonomyLabel.fill("重複分類");
    await submit.focus();
    await page.keyboard.press("Enter");
    await page.locator("#taxonomy-id-error").waitFor();
    assert.equal(await taxonomyId.getAttribute("aria-invalid"), "true");
    assert.equal(await taxonomyId.getAttribute("aria-describedby"), "taxonomy-id-error");
    assert.equal(await page.locator("#taxonomy-id-error").textContent(), "Taxonomy 或 term 已存在，或其生命週期狀態不允許此操作。");
    const missingTicket = await client.mintBrowserTicket();
    assert.equal(missingTicket.ok, true, missingTicket.ok ? "" : missingTicket.error.code);
    if (!missingTicket.ok) return;
    await page.goto(`${runtime.value.origin}/cms/taxonomies/missing#${missingTicket.value.ticket}`, { waitUntil: "networkidle" });
    await page.getByRole("heading", { name: "分類詳情", exact: true }).waitFor();
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const missing = page.locator('p[role="alert"]').filter({ hasText: "找不到分類。" });
    await missing.waitFor();
    assert.equal(await missing.textContent(), "找不到分類。");
    await page.setViewportSize({ width: 375, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  } finally {
    await browser?.close();
    await runtime.value.close();
  }
});

test("真實 CMS runtime 以既有 taxonomy 呈現 catalog 與 term 表格", async (context) => {
  const root = mkdtempSync(path.join(tmpdir(), "cms-taxonomy-tables-browser-"));
  context.after(() => { rmSync(root, { recursive: true, force: true }); });
  const repositoryRoot = path.resolve(import.meta.dirname, "../../../");
  const databasePath = path.join(root, "cms.sqlite");
  const mediaRoot = path.join(root, "media");
  const pluginsRoot = path.join(root, "plugins");
  const themesRoot = path.join(root, "themes");
  const credentialRoot = path.join(root, "credential");
  mkdirSync(mediaRoot, { mode: 0o700 });
  mkdirSync(pluginsRoot, { mode: 0o700 });
  mkdirSync(themesRoot, { mode: 0o700 });
  assert.equal(runDbMigrate(["--database", databasePath], capture().io), 0);
  const opened = openPersistence({ databasePath });
  assert.equal(opened.ok, true, opened.ok ? "" : opened.error.code);
  if (!opened.ok) return;
  try {
    const taxonomy = createTaxonomy({ persistence: opened.value });
    // catalog 依 taxonomyId code unit 排序，因此先建立排序在後的 topics 才能證明順序來自 Taxonomy 而非建立順序。
    const topics = taxonomy.createTaxonomy({ contract: "taxonomy-create-request/v1", taxonomyId: "topics", label: "主題" });
    assert.equal(topics.ok, true, topics.ok ? "" : topics.error.code);
    if (!topics.ok) return;
    const authors = taxonomy.createTaxonomy({ contract: "taxonomy-create-request/v1", taxonomyId: "authors", label: "作者" });
    assert.equal(authors.ok, true, authors.ok ? "" : authors.error.code);
    if (!authors.ok) return;
    // term 依 order 排序；先建立 order 較大的 beta，再建立 alpha。
    const beta = taxonomy.executeCommand("topics", { contract: "taxonomy-command/v1", kind: "create-term", expectedStateDigest: topics.value.stateDigest, termId: "beta", label: "Beta", slug: "beta", order: 20 });
    assert.equal(beta.ok, true, beta.ok ? "" : beta.error.code);
    if (!beta.ok) return;
    const alpha = taxonomy.executeCommand("topics", { contract: "taxonomy-command/v1", kind: "create-term", expectedStateDigest: beta.value.snapshot.stateDigest, termId: "alpha", label: "Alpha", slug: "alpha", order: 10 });
    assert.equal(alpha.ok, true, alpha.ok ? "" : alpha.error.code);
    if (!alpha.ok) return;
    const retired = taxonomy.executeCommand("topics", { contract: "taxonomy-command/v1", kind: "retire-term", expectedStateDigest: alpha.value.snapshot.stateDigest, termId: "beta" });
    assert.equal(retired.ok, true, retired.ok ? "" : retired.error.code);
    if (!retired.ok) return;
  } finally {
    opened.value.close();
  }
  assert.equal(await runThemePackage(["--id", "study-notes", "--installed-themes-root", themesRoot], capture().io), 0);
  assert.equal(await runThemeActivate(["--database", databasePath, "--installed-themes-root", themesRoot, "--id", "study-notes"], capture().io), 0);
  const credential = createLocalAuthoringCredentialAuthority({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
  assert.equal((await credential.transition("provision")).ok, true);
  const runtime = await startCmsRuntime({ repositoryRoot, databasePath, mediaRoot, installedPluginsRoot: pluginsRoot, installedThemesRoot: themesRoot, cmsAssetsRoot: path.join(repositoryRoot, "dist", "cms"), credential: { homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }, logger: () => undefined });
  assert.equal(runtime.ok, true, runtime.ok ? "" : runtime.error.code);
  if (!runtime.ok) return;
  let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
  try {
    const minted = await createLocalAuthoringClient({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }).mintBrowserTicket();
    assert.equal(minted.ok, true, minted.ok ? "" : minted.error.code);
    if (!minted.ok) return;
    browser = await chromium.launch();
    const page = await (await browser.newContext({ serviceWorkers: "block", acceptDownloads: false, viewport: { width: 1440, height: 900 } })).newPage();
    await page.goto(`${runtime.value.origin}/cms/taxonomies#${minted.value.ticket}`, { waitUntil: "networkidle" });
    await page.getByRole("heading", { name: "分類全覽", exact: true }).waitFor();
    const catalog = page.getByRole("table", { name: "所有分類", exact: true });
    await catalog.waitFor();
    assert.deepEqual(await catalog.getByRole("row").allInnerTexts(), ["名稱\tTaxonomy ID", "作者\tauthors", "主題\ttopics"]);
    await page.getByRole("link", { name: "主題", exact: true }).click();
    await page.getByRole("heading", { name: "分類：主題", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/taxonomies/topics");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const terms = page.getByRole("table", { name: "所有 terms", exact: true });
    await terms.waitFor();
    assert.deepEqual(await terms.getByRole("row").allInnerTexts(), ["名稱\tSlug\t順序\t狀態", "Alpha\talpha\t10\t使用中", "Beta\tbeta\t20\t已停用"]);
    await page.setViewportSize({ width: 375, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  } finally {
    await browser?.close();
    await runtime.value.close();
  }
});

test("真實 CMS runtime 在 CAS reload 後保留 taxonomy binding 並發布", async (context) => {
  const root = mkdtempSync(path.join(tmpdir(), "cms-taxonomy-binding-browser-"));
  context.after(() => { rmSync(root, { recursive: true, force: true }); });
  const repositoryRoot = path.resolve(import.meta.dirname, "../../../");
  const databasePath = path.join(root, "cms.sqlite");
  const mediaRoot = path.join(root, "media");
  const pluginsRoot = path.join(root, "plugins");
  const themesRoot = path.join(root, "themes");
  const credentialRoot = path.join(root, "credential");
  mkdirSync(mediaRoot, { mode: 0o700 });
  mkdirSync(pluginsRoot, { mode: 0o700 });
  mkdirSync(themesRoot, { mode: 0o700 });
  assert.equal(runDbMigrate(["--database", databasePath], capture().io), 0);
  const opened = openPersistence({ databasePath });
  assert.equal(opened.ok, true, opened.ok ? "" : opened.error.code);
  if (!opened.ok) return;
  try {
    const taxonomy = createTaxonomy({ persistence: opened.value });
    const created = taxonomy.createTaxonomy({ contract: "taxonomy-create-request/v1", taxonomyId: "topics", label: "Topics" });
    assert.equal(created.ok, true, created.ok ? "" : created.error.code);
    if (!created.ok) return;
    const alpha = taxonomy.executeCommand("topics", { contract: "taxonomy-command/v1", kind: "create-term", expectedStateDigest: created.value.stateDigest, termId: "alpha", label: "Alpha", slug: "alpha", order: 10 });
    assert.equal(alpha.ok, true, alpha.ok ? "" : alpha.error.code);
    if (!alpha.ok) return;
    const beta = taxonomy.executeCommand("topics", { contract: "taxonomy-command/v1", kind: "create-term", expectedStateDigest: alpha.value.snapshot.stateDigest, termId: "beta", label: "Beta", slug: "beta", order: 20 });
    assert.equal(beta.ok, true, beta.ok ? "" : beta.error.code);
    if (!beta.ok) return;
  } finally {
    opened.value.close();
  }
  assert.equal(await runThemePackage(["--id", "study-notes", "--installed-themes-root", themesRoot], capture().io), 0);
  assert.equal(await runThemeActivate(["--database", databasePath, "--installed-themes-root", themesRoot, "--id", "study-notes"], capture().io), 0);
  const credential = createLocalAuthoringCredentialAuthority({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
  assert.equal((await credential.transition("provision")).ok, true);
  const runtime = await startCmsRuntime({ repositoryRoot, databasePath, mediaRoot, installedPluginsRoot: pluginsRoot, installedThemesRoot: themesRoot, cmsAssetsRoot: path.join(repositoryRoot, "dist", "cms"), credential: { homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }, logger: () => undefined });
  assert.equal(runtime.ok, true, runtime.ok ? "" : runtime.error.code);
  if (!runtime.ok) return;
  const client = createLocalAuthoringClient({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
  const entryId = "taxonomy-bound-entry";
  const content = (title: string, text: string) => ({ contract: "site-content/v1" as const, title, blocks: [{ kind: "article" as const, text }], seo: {} });
  let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
  try {
    const seeded = await client.saveRevision({ entryId, request: { contract: "save-revision-request/v1", revisionId: "bound-alpha", operationId: "bound-alpha-save", expectedCurrentRevisionId: null, schemaIdentity: { schemaId: "site-content", version: 1 }, content: content("Taxonomy Alpha", "以 Alpha 建立。"), route: "/taxonomy-bound-entry", assetVersions: [], taxonomyTerms: [{ taxonomyId: "topics", termId: "alpha" }] } });
    assert.equal(seeded.ok, true, seeded.ok ? "" : seeded.error.code);
    if (!seeded.ok) return;
    const initiallyPublished = await client.publishRevision({ entryId, request: { contract: "publish-revision-request/v1", expectedCurrentRevisionId: "bound-alpha", operationId: "bound-alpha-publish" } });
    assert.equal(initiallyPublished.ok, true, initiallyPublished.ok ? "" : initiallyPublished.error.code);
    if (!initiallyPublished.ok) return;
    const minted = await client.mintBrowserTicket();
    assert.equal(minted.ok, true, minted.ok ? "" : minted.error.code);
    if (!minted.ok) return;
    browser = await chromium.launch();
    const page = await (await browser.newContext({ serviceWorkers: "block", acceptDownloads: false, viewport: { width: 1440, height: 900 } })).newPage();
    await page.goto(`${runtime.value.origin}/cms/entries/${entryId}#${minted.value.ticket}`, { waitUntil: "networkidle" });
    await page.getByRole("heading", { name: "編輯文章", exact: true }).waitFor();
    const competing = await client.saveRevision({ entryId, request: { contract: "save-revision-request/v1", revisionId: "bound-beta-external", operationId: "bound-beta-external-save", expectedCurrentRevisionId: "bound-alpha", schemaIdentity: { schemaId: "site-content", version: 1 }, content: content("Taxonomy Beta 外部更新", "以 Beta 更新。"), route: "/taxonomy-bound-entry", assetVersions: [], taxonomyTerms: [{ taxonomyId: "topics", termId: "beta" }] } });
    assert.equal(competing.ok, true, competing.ok ? "" : competing.error.code);
    if (!competing.ok) return;
    await page.getByRole("textbox", { name: "標題", exact: true }).fill("過期 CMS 修改");
    await page.getByRole("button", { name: "儲存", exact: true }).click();
    await page.getByText("內容已由另一個頁面更新。", { exact: true }).waitFor();
    await page.getByRole("button", { name: "重新載入文章", exact: true }).click();
    await page.waitForFunction(() => Array.from(document.querySelectorAll("input")).some((input) => input.value === "Taxonomy Beta 外部更新"));
    await page.getByRole("textbox", { name: "標題", exact: true }).fill("CMS 保留 Beta binding");
    assert.equal(await page.getByRole("button", { name: "儲存", exact: true }).isDisabled(), false);
    await page.getByRole("button", { name: "儲存", exact: true }).click();
    await page.getByText("已儲存。", { exact: true }).waitFor();
    await page.getByRole("button", { name: "發布", exact: true }).click();
    await page.getByRole("button", { name: "確認發布", exact: true }).click();
    await page.getByText("已發布。", { exact: true }).waitFor();
  } finally {
    await browser?.close();
    await runtime.value.close();
  }
  const verified = openPersistence({ databasePath });
  assert.equal(verified.ok, true, verified.ok ? "" : verified.error.code);
  if (!verified.ok) return;
  try {
    const pointers = verified.value.getEntryPointers(entryId);
    assert.equal(pointers.ok, true, pointers.ok ? "" : pointers.error.code);
    if (!pointers.ok || pointers.value.publishedRevisionId === undefined) return;
    const current = verified.value.getRevisionTaxonomyBindings({ entryId, revisionId: pointers.value.currentRevisionId });
    const published = verified.value.getRevisionTaxonomyBindings({ entryId, revisionId: pointers.value.publishedRevisionId });
    assert.equal(current.ok && published.ok, true);
    if (!current.ok || !published.ok) return;
    const evidence = { taxonomyId: "topics", termId: "beta", label: "Beta", slug: "beta", order: 20 };
    const evidenceBytes = canonicalJsonBytes(evidence);
    assert.equal(evidenceBytes.ok, true);
    if (!evidenceBytes.ok) return;
    const expected = [{ taxonomyId: "topics", termId: "beta", evidence, evidenceDigest: sha256Digest(evidenceBytes.value) }];
    assert.deepEqual(current.value, expected);
    assert.deepEqual(published.value, expected);
  } finally {
    verified.value.close();
  }
});

test("真實 CMS runtime 完成 Content Type empty、create 與 detail/history browser/a11y journey", async (context) => {
  const root = mkdtempSync(path.join(tmpdir(), "cms-content-type-browser-"));
  context.after(() => { rmSync(root, { recursive: true, force: true }); });
  const repositoryRoot = path.resolve(import.meta.dirname, "../../../");
  const databasePath = path.join(root, "cms.sqlite");
  const mediaRoot = path.join(root, "media");
  const pluginsRoot = path.join(root, "plugins");
  const themesRoot = path.join(root, "themes");
  const credentialRoot = path.join(root, "credential");
  mkdirSync(mediaRoot, { mode: 0o700 });
  mkdirSync(pluginsRoot, { mode: 0o700 });
  mkdirSync(themesRoot, { mode: 0o700 });
  assert.equal(migrateDatabase({ databasePath }).ok, true);
  assert.equal(await runThemePackage(["--id", "study-notes", "--installed-themes-root", themesRoot], capture().io), 0);
  assert.equal(await runThemeActivate(["--database", databasePath, "--installed-themes-root", themesRoot, "--id", "study-notes"], capture().io), 0);
  const credential = createLocalAuthoringCredentialAuthority({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
  assert.equal((await credential.transition("provision")).ok, true);
  const runtime = await startCmsRuntime({ repositoryRoot, databasePath, mediaRoot, installedPluginsRoot: pluginsRoot, installedThemesRoot: themesRoot, cmsAssetsRoot: path.join(repositoryRoot, "dist", "cms"), credential: { homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }, logger: () => undefined });
  assert.equal(runtime.ok, true, runtime.ok ? "" : runtime.error.code);
  if (!runtime.ok) return;
  let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
  try {
    const minted = await createLocalAuthoringClient({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }).mintBrowserTicket();
    assert.equal(minted.ok, true, minted.ok ? "" : minted.error.code);
    if (!minted.ok) return;
    browser = await chromium.launch();
    const page = await (await browser.newContext({ serviceWorkers: "block", acceptDownloads: false, viewport: { width: 1440, height: 900 } })).newPage();
    await page.goto(`${runtime.value.origin}/cms#${minted.value.ticket}`, { waitUntil: "networkidle" });
    const contentTypes = page.getByRole("link", { name: "內容類型", exact: true });
    await contentTypes.focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "內容類型全覽", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/content-types");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    await page.getByRole("link", { name: "跳到主標題", exact: true }).focus();
    await page.keyboard.press("Enter");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    await page.getByText("尚無內容類型。", { exact: false }).waitFor();
    const first = page.getByRole("link", { name: "建立第一個內容類型", exact: true });
    await first.focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "建立內容類型", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/content-types/new");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    await page.getByRole("textbox", { name: "Schema ID", exact: true }).fill("invalid/id");
    await page.getByRole("button", { name: "建立內容類型", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.getByText("Schema ID 只能使用英數字、句點、底線、連字號或波浪號。", { exact: true }).waitFor();
    assert.equal(await page.getByRole("textbox", { name: "Schema ID", exact: true }).getAttribute("aria-describedby"), "content-type-schema-id-error");
    assert.notEqual(await page.getByRole("textbox", { name: "JSON Schema", exact: true }).getAttribute("aria-invalid"), "true");
    assert.equal(await page.getByRole("textbox", { name: "JSON Schema", exact: true }).getAttribute("aria-describedby"), null);
    await page.getByRole("textbox", { name: "Schema ID", exact: true }).fill("study-note");
    assert.notEqual(await page.getByRole("textbox", { name: "Schema ID", exact: true }).getAttribute("aria-invalid"), "true");
    assert.equal(await page.getByRole("textbox", { name: "Schema ID", exact: true }).getAttribute("aria-describedby"), null);
    await page.getByRole("textbox", { name: "JSON Schema", exact: true }).fill("{");
    await page.getByRole("button", { name: "建立內容類型", exact: true }).focus();
    await page.keyboard.press("Enter");
    const validationError = page.getByText("請輸入有效 JSON Schema。", { exact: true });
    await validationError.waitFor();
    assert.equal(await page.getByRole("textbox", { name: "JSON Schema", exact: true }).getAttribute("aria-describedby"), "content-type-schema-error");
    assert.notEqual(await page.getByRole("textbox", { name: "Schema ID", exact: true }).getAttribute("aria-invalid"), "true");
    assert.equal(await page.getByRole("textbox", { name: "Schema ID", exact: true }).getAttribute("aria-describedby"), null);
    await page.getByRole("textbox", { name: "JSON Schema", exact: true }).fill("{\"type\":\"object\",\"additionalProperties\":false}");
    assert.notEqual(await page.getByRole("textbox", { name: "JSON Schema", exact: true }).getAttribute("aria-invalid"), "true");
    assert.equal(await page.getByRole("textbox", { name: "JSON Schema", exact: true }).getAttribute("aria-describedby"), null);
    await page.getByRole("button", { name: "建立內容類型", exact: true }).focus();
    await page.keyboard.press("Enter");
    await page.getByRole("heading", { name: "內容類型：study-note", exact: true }).waitFor();
    assert.equal(new URL(page.url()).pathname, "/cms/content-types/study-note");
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    assert.equal(await page.evaluate(() => document.activeElement?.id), "page-title");
    await page.getByRole("heading", { name: "版本歷程", exact: true }).waitFor();
    await page.getByText("版本 1（目前）", { exact: true }).waitFor();
    await page.getByText("\"additionalProperties\": false", { exact: false }).waitFor();
    await page.setViewportSize({ width: 375, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  } finally {
    await browser?.close();
    await runtime.value.close();
  }
});

test("真實 CMS runtime 以單一 catalog snapshot 呈現 immutable Content Type history", async (context) => {
  const root = mkdtempSync(path.join(tmpdir(), "cms-content-type-history-"));
  context.after(() => { rmSync(root, { recursive: true, force: true }); });
  const repositoryRoot = path.resolve(import.meta.dirname, "../../../");
  const databasePath = path.join(root, "cms.sqlite");
  const mediaRoot = path.join(root, "media");
  const pluginsRoot = path.join(root, "plugins");
  const themesRoot = path.join(root, "themes");
  const credentialRoot = path.join(root, "credential");
  mkdirSync(mediaRoot, { mode: 0o700 });
  mkdirSync(pluginsRoot, { mode: 0o700 });
  mkdirSync(themesRoot, { mode: 0o700 });
  assert.equal(migrateDatabase({ databasePath }).ok, true);
  const version1Schema = canonicalJsonBytes({ type: "object", title: "版本一" });
  const version2Schema = canonicalJsonBytes({ type: "object", title: "版本二", additionalProperties: false });
  assert.equal(version1Schema.ok && version2Schema.ok, true);
  if (!version1Schema.ok || !version2Schema.ok) return;
  const persistence = openPersistence({ databasePath });
  assert.equal(persistence.ok, true, persistence.ok ? "" : persistence.error.code);
  if (!persistence.ok) return;
  try {
    assert.equal(persistence.value.registerSchemaVersion({ identity: { schemaId: "note", version: 1 }, schemaBytes: version1Schema.value, schemaDigest: sha256Digest(version1Schema.value) }).ok, true);
    assert.equal(persistence.value.registerSchemaVersion({ identity: { schemaId: "note", version: 2 }, schemaBytes: version2Schema.value, schemaDigest: sha256Digest(version2Schema.value) }).ok, true);
  } finally {
    persistence.value.close();
  }
  const version2Digest = sha256Digest(version2Schema.value);
  assert.equal(await runThemePackage(["--id", "study-notes", "--installed-themes-root", themesRoot], capture().io), 0);
  assert.equal(await runThemeActivate(["--database", databasePath, "--installed-themes-root", themesRoot, "--id", "study-notes"], capture().io), 0);
  const credential = createLocalAuthoringCredentialAuthority({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") });
  assert.equal((await credential.transition("provision")).ok, true);
  const runtime = await startCmsRuntime({ repositoryRoot, databasePath, mediaRoot, installedPluginsRoot: pluginsRoot, installedThemesRoot: themesRoot, cmsAssetsRoot: path.join(repositoryRoot, "dist", "cms"), credential: { homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }, logger: () => undefined });
  assert.equal(runtime.ok, true, runtime.ok ? "" : runtime.error.code);
  if (!runtime.ok) return;
  let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
  try {
    const minted = await createLocalAuthoringClient({ homeDirectory: credentialRoot, xdgConfigHome: path.join(credentialRoot, "config") }).mintBrowserTicket();
    assert.equal(minted.ok, true, minted.ok ? "" : minted.error.code);
    if (!minted.ok) return;
    browser = await chromium.launch();
    const page = await (await browser.newContext({ serviceWorkers: "block", acceptDownloads: false, viewport: { width: 1440, height: 900 } })).newPage();
    await page.goto(`${runtime.value.origin}/cms/content-types/note#${minted.value.ticket}`, { waitUntil: "networkidle" });
    await page.getByRole("heading", { name: "內容類型：note", exact: true }).waitFor();
    await page.waitForFunction(() => document.activeElement?.id === "page-title");
    const history = page.locator('section[aria-labelledby="content-type-history"] li');
    await history.first().waitFor();
    assert.deepEqual(await history.allTextContents(), ["版本 2（目前）", "版本 1"]);
    assert.equal(await history.nth(0).getAttribute("aria-current"), "true");
    assert.equal(await history.nth(1).getAttribute("aria-current"), null);
    await page.getByText(version2Digest, { exact: true }).waitFor();
    await page.getByText("\"title\": \"版本二\"", { exact: false }).waitFor();
    assert.equal(await page.getByText("\"title\": \"版本一\"", { exact: false }).count(), 0);
  } finally {
    await browser?.close();
    await runtime.value.close();
  }
});
