import { canonicalJsonBytes, copyBytes, sha256Digest } from "../foundation/index.js";
import type { AssetVersionIdentity, DataMedia, DataMediaFailureCode, DataMediaPersistence, DataMediaResult, ImportLocalMediaInput, MediaImportIntent, MediaObjectStore, ReadyAssetVersion } from "./contracts.js";

const messages: Readonly<Record<DataMediaFailureCode, string>> = { INVALID_MEDIA_INPUT: "請提供有效的 media import 輸入。", MEDIA_ROOT_FAILURE: "Media storage root 無法安全使用。", MEDIA_IMPORT_CONFLICT: "Media import identity 與既有紀錄衝突。", MEDIA_STAGING_FAILURE: "Media bytes 尚未完成 staging。", MEDIA_PENDING_COMMIT_FAILURE: "Media import intent 尚未提交為 pending。", MEDIA_PROMOTION_FAILURE: "Media object 尚未完成 promotion。", MEDIA_FINAL_VERIFICATION_FAILURE: "Host 最終 media object 驗證失敗。", MEDIA_READY_COMMIT_FAILURE: "Media asset version 尚未提交為 ready。", MEDIA_VERSION_UNAVAILABLE: "指定的 media asset version 尚不可用。" };
export function createDataMedia({ persistence, objectStore }: Readonly<{ persistence: DataMediaPersistence; objectStore: MediaObjectStore }>): DataMedia {
  const fail = <T>(code: DataMediaFailureCode): DataMediaResult<T> => ({ ok: false, error: { code, owner: "DataMedia", subjectIds: [], remediation: { kind: "message", message: messages[code] } } });
  const resolve = (identity: AssetVersionIdentity): DataMediaResult<ReadyAssetVersion> => { const record = persistence.getReadyAssetVersion(identity); if (!record.ok) return fail("MEDIA_VERSION_UNAVAILABLE"); const verified = objectStore.verifyEvidence({ objectDigest: record.value.objectDigest, byteLength: record.value.byteLength }); return verified.ok ? { ok: true, value: { ...record.value, identity: { ...record.value.identity }, metadataBytes: copyBytes(record.value.metadataBytes) } } : fail("MEDIA_VERSION_UNAVAILABLE"); };
  return { importLocal(input) { if (!valid(input)) return fail("INVALID_MEDIA_INPUT"); const metadata = canonicalJsonBytes(input.metadata); if (!metadata.ok) return fail("INVALID_MEDIA_INPUT"); const evidence = { objectDigest: sha256Digest(input.bytes), byteLength: input.bytes.byteLength }; const intent: MediaImportIntent = { importId: input.importId, identity: { assetId: input.assetId, assetVersionId: input.assetVersionId }, ...evidence, metadataBytes: copyBytes(metadata.value), metadataDigest: sha256Digest(metadata.value) }; const staged = objectStore.stage({ importId: input.importId, bytes: copyBytes(input.bytes), evidence }); if (!staged.ok) return fail("MEDIA_STAGING_FAILURE"); const pending = persistence.createMediaImportIntent(intent); if (!pending.ok) return fail("MEDIA_PENDING_COMMIT_FAILURE"); const final = objectStore.promote(staged.value, evidence); if (!final.ok) return fail("MEDIA_PROMOTION_FAILURE"); if (!objectStore.verifyFinal(final.value, evidence).ok) return fail("MEDIA_FINAL_VERIFICATION_FAILURE"); if (!objectStore.releaseStage(staged.value, final.value).ok) return fail("MEDIA_FINAL_VERIFICATION_FAILURE"); const ready = persistence.commitReadyAssetVersion(intent); return ready.ok ? { ok: true, value: ready.value } : fail("MEDIA_READY_COMMIT_FAILURE"); }, getReadyAssetVersion: resolve, requireReadyAssetVersions(identities) { if (!Array.isArray(identities)) return fail("INVALID_MEDIA_INPUT"); const values: ReadyAssetVersion[] = []; for (const identity of identities) { const value = resolve(identity); if (!value.ok) return fail("MEDIA_VERSION_UNAVAILABLE"); values.push(value.value); } return { ok: true, value: values }; }, resolvePublishedSelection(entryId) { if (typeof entryId !== "string" || entryId.length === 0) return fail("INVALID_MEDIA_INPUT"); const pointer = persistence.getEntryPointers(entryId); if (!pointer.ok || pointer.value.publishedRevisionId === undefined) return fail("MEDIA_VERSION_UNAVAILABLE"); const references = persistence.getRevisionReferences({ entryId, revisionId: pointer.value.publishedRevisionId }); if (!references.ok) return fail("MEDIA_VERSION_UNAVAILABLE"); const assets: ReadyAssetVersion[] = []; for (const reference of references.value) { const asset = resolve(reference.assetVersion); if (!asset.ok) return fail("MEDIA_VERSION_UNAVAILABLE"); assets.push(asset.value); } return { ok: true, value: { entryId, revisionId: pointer.value.publishedRevisionId, assets } }; } };
}
function valid(input: ImportLocalMediaInput): boolean { return typeof input.importId === "string" && input.importId.length > 0 && typeof input.assetId === "string" && input.assetId.length > 0 && typeof input.assetVersionId === "string" && input.assetVersionId.length > 0 && input.bytes instanceof Uint8Array; }
